---
title: "R Notebook"
output: html_notebook
---


```{r}
library(elsasserlib)
library(ggpubr)
library(reshape)
library(dplyr)
library(ggrepel)
```

```{r fig.width=4, fig.height=2}
tbl <- read.table('Kumar_2020_master_gene_table_rnaseq_shrunk_plus_annotations.tsv',sep = "\t",header = T)
tbl <- tbl[!duplicated(tbl$name),]

tbl$sig_Ni_EZH2i_up <- (tbl$RNASeq_DS_EZH2i_vs_Ni_log2FoldChange > 1) & (tbl$RNASeq_DS_EZH2i_vs_Ni_padj < 0.05)
tbl$sig_Ni_EZH2i_down <- (tbl$RNASeq_DS_EZH2i_vs_Ni_log2FoldChange < -1) & (tbl$RNASeq_DS_EZH2i_vs_Ni_padj < 0.05)

tbl$sig_Ni_EZH2i_up[is.na(tbl$sig_Ni_EZH2i_up)] <- F
tbl$sig_Ni_EZH2i_down[is.na(tbl$sig_Ni_EZH2i_down)] <- F

krendl_4TF <- unlist(read.table('Krendl2017.4TFtargets.txt',sep = "\t"))
krendl_3TF <- unlist(read.table('Krendl2017.3TFtargets.txt',sep = "\t"))
krendl_tbl <- read.table('Krendl2017.STable4.txt',header=T, sep = "\t")
krendl_1TF <- unlist(krendl_tbl$gene[krendl_tbl$gata2 | krendl_tbl$gata3])
krendl_2TF <- unlist(krendl_tbl$gene[krendl_tbl$gata2 & krendl_tbl$gata3])

tbl$TF <- factor(x = "none", levels=c("none","GATA3","3TF","4TF"))
tbl$TF[tbl$name %in% krendl_1TF] <- "GATA3"
tbl$TF[tbl$name %in% krendl_3TF] <- "3TF"
tbl$TF[tbl$name %in% krendl_4TF] <- "4TF"

ggboxplot(tbl[tbl$sig_Ni_EZH2i_up,],x = "TF",y="RNASeq_DS_EZH2i_vs_Ni_log2FoldChange", color="TF", palette = "aaas", add=c("jitter"), add.params = list(alpha=0.2,size=0.5))
```
```{r}

```
