---
title: "R Notebook"
output: html_notebook
---


```{r}
library(elsasserlib)
library(ggpubr)
library(reshape)
library(dplyr)
library(ggrepel)
```

```{r fig.width=8, fig.height=5}
tbl <- read.table('./data/meta/Kumar_2020_master_gene_table_rnaseq_shrunk_annotated.tsv',sep = "\t",header = T)
tbl <- tbl[!duplicated(tbl$name),]

tbl$sig_Ni_EZH2i_up <- (tbl$RNASeq_DS_EZH2i_vs_Ni_log2FoldChange > 1) & (tbl$RNASeq_DS_EZH2i_vs_Ni_padj < 0.05)
tbl$sig_Ni_EZH2i_down <- (tbl$RNASeq_DS_EZH2i_vs_Ni_log2FoldChange < -1) & (tbl$RNASeq_DS_EZH2i_vs_Ni_padj < 0.05)

tbl$sig_Ni_EZH2i_up[is.na(tbl$sig_Ni_EZH2i_up)] <- F
tbl$sig_Ni_EZH2i_down[is.na(tbl$sig_Ni_EZH2i_down)] <- F

up <- select(tbl[tbl$sig_Ni_EZH2i_up,],"name","k27_bivalency_grp",contains("mean_cov"))
down <- select(tbl[tbl$sig_Ni_EZH2i_down,],"name","k27_bivalency_grp",contains("mean_cov"))
               
up$class <- "Ni_EZH2i_up"
down$class <- "Ni_EZH2i_down"

mdf <- rbind(up,down)

itbl <- table(select(mdf,"k27_bivalency_grp","class"))

itbl
colSums(itbl)
```

```{r}
krendl_4TF <- unlist(read.table('Krendl2017.4TFtargets.txt',sep = "\t"))
krendl_3TF <- unlist(read.table('Krendl2017.3TFtargets.txt',sep = "\t"))
krendl_tbl <- read.table('Krendl2017.STable4.txt',header=T, sep = "\t")
krendl_1TF <- unlist(krendl_tbl$gene[krendl_tbl$gata2 | krendl_tbl$gata3])
krendl_2TF <- unlist(krendl_tbl$gene[krendl_tbl$gata2 & krendl_tbl$gata3])

mdf$H3K4me3 <- mdf$H3K4m3_Ni_mean_cov > 10
mdf$TF <- "none"
#mdf$TF[mdf$H3K4me3] <- "H3K4me3"
mdf$TF[mdf$k27_bivalency_grp != "None"] <- "bivalent"
mdf$TF[mdf$name %in% krendl_1TF] <- "1TF"
mdf$TF[mdf$name %in% krendl_2TF] <- "2TF"
mdf$TF[mdf$name %in% krendl_3TF] <- "3TF"
mdf$TF[mdf$name %in% krendl_4TF] <- "4TF"

table(select(mdf,"TF","H3K4me3"))
```

```{r}
table(select(mdf,"TF","class"))
colSums(table(select(mdf,"TF","class")))
```

```{r}
fig5b <- c("EPAS1","MSX2","GATA3","CLDN4","GATA2","IGF2","CDX2","SLC40A1","KRT7","FRZB","CGA","ERP27","KRT23","CGB5","VGLL1","TP63")

intersect(fig5b,krendl_tbl$gene[krendl_tbl$gata2 | krendl_tbl$gata3])
```


```{r}
tbl$sig_Pr_EZH2i_up <- (tbl$RNASeq_DS_EZH2i_vs_Pr_log2FoldChange > 1) & (tbl$RNASeq_DS_EZH2i_vs_Pr_padj < 0.05)

tbl$sig_Ni_EZH2i_up[is.na(tbl$sig_Ni_EZH2i_up)] <- F
tbl$sig_Pr_EZH2i_up[is.na(tbl$sig_Pr_EZH2i_up)] <- F

tbl$sig_both_EZH2i_up <- tbl$sig_Ni_EZH2i_up & tbl$sig_Pr_EZH2i_up
tbl$sig_Ni_EZH2i_up[tbl$sig_both_EZH2i_up] <- F
tbl$sig_Pr_EZH2i_up[tbl$sig_both_EZH2i_up] <- F

Ni_up <- select(tbl[tbl$sig_Ni_EZH2i_up,],"name","k27_bivalency_grp",contains("mean_cov"))
Pr_up <- select(tbl[tbl$sig_Pr_EZH2i_up,],"name","k27_bivalency_grp",contains("mean_cov"))
both_up <- select(tbl[tbl$sig_both_EZH2i_up,],"name","k27_bivalency_grp",contains("mean_cov"))
   
               
Ni_up$class <- "Ni_EZH2i_up"
Pr_up$class <- "Pr_EZH2i_up"
both_up$class <- "both_EZH2i_up"

mdf <- rbind(Ni_up,Pr_up,both_up)

itbl <- table(select(mdf,"k27_bivalency_grp","class"))

itbl
colSums(itbl)

```
```{r}

tbl$opp_EZH2i <- tbl$sig_Ni_EZH2i_down & tbl$sig_Pr_EZH2i_up

table(select(tbl,"k27_bivalency_grp","intermediate_signature"))
tbl$name[tbl$opp_EZH2i]
```

```{r fig.width=5, fig.height=5}

mdf <- melt(select(tbl[tbl$opp_EZH2i,],"name","k27_bivalency_grp","intermediate_signature",contains("TPM") & contains("R1")),id.vars = c("name","k27_bivalency_grp","intermediate_signature"))

mdf <- cbind(mdf,colsplit(mdf$variable,"_",c("RNASeq","TPM","state","treatment"))) 
mdf$treatment <- gsub(mdf$treatment,pattern = "R1",replacement = "NT") 
mdf$sample <- paste0(mdf$state," ",mdf$treatment)
mdf$lg2 <- log2(mdf$value)

mdf$sample <- factor(mdf$sample, levels=c("Ni NT","Ni EZH2i","Pr EZH2i","Pr NT"))

ggplot(data=mdf, aes(x=sample, y=lg2, group=name)) +
  geom_line() +
  geom_point() +
  facet_wrap(facets = ~ name)

ggstripchart(mdf,x="name",y="lg2",color="sample", size=5, palette="npg", jitter = 0,orientation = c("horizontal")) +
  geom_line()
ggsave("Fig4_EZH2i_intermediate_genes.pdf")
```

```{r}

inter.up50 <- unlist(read.table(file = "Messmer_intermediate_up.top50.txt"))
inter.down50 <- unlist(read.table(file = "Messmer_intermediate_down.top50.txt"))

tbl$messmer <- "none"
tbl$messmer[tbl$name %in% inter.up50] <- "top50_up"
tbl$messmer[tbl$name %in% inter.down50] <- "top50_down"

table(select(tbl,"k27_bivalency_grp","messmer"))

colSums(table(select(tbl,"k27_bivalency_grp","messmer")))
```
