---
title: "Figure 3."
author: "Carmen Navarro"
date: "2021-07-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Summary

This is the supplementary notebook for figure 3.

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(rtracklayer)
library(tidyverse)
library(effsize)
library(ggpubr)
library(ggrastr)
library(cowplot)
library(dplyr)

source("./code/globals.R")
source("./code/heatmap_panels.R")
source("./code/heatmaply_functions.R")

knitr::opts_chunk$set(dev = c('png', 'my_svg'), fig.ext = c("png", "svg"), fig.width = 8, fig.height = 8)

genes <-
  read.table(
    "./data/meta/Kumar_2020_master_gene_table_rnaseq_shrunk_plus_annotations.tsv",
    header = T,
    sep = "\t",
    colClasses = c(rep("character", 5), rep("numeric", 86), rep("factor", 4))
  )

```

# H3K27m3 promoter volcano plot
```{r h3k27m3-promoter-volcano, fig.width = 7, fig.height = 7}
genes_tss <- makeGRangesFromDataFrame(genes, keep.extra.columns = T)
court_peaks <- import("./data/bed/Bivalent_Court2017.hg38.bed")
court_tss <- subsetByOverlaps(genes_tss, court_peaks)

court_tss_df <- data.frame(court_tss)

ggplot(genes, aes(x=H3K27m3_DS_Pr_vs_Ni_log2FoldChange, y=-log10(H3K27m3_DS_Pr_vs_Ni_padj))) +
    rasterise(geom_point(size = 1, alpha = 0.7, color = "gray"), dpi = 300) +
    theme_default(base_size = 12) +

    rasterise(geom_point(data = court_tss_df, size = 1, alpha = 0.8, color = "black"), dpi = 300) +
      labs(x = "Log2 FC (primed/naive)",
         y = "Log10 pval", title = "Promoter H3K27m3 - Court 2017 bivalent in black") +
    geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
    geom_vline(xintercept = 0) +
    coord_cartesian(xlim = c(-6,6), ylim = c(0, 20))

```


# H3K27m3 groups heatmap panels

```{r heatmap-groups-1, warning=F, fig.width = 14, fig.height = 14}

genes_loci <- import("./data/bed/Kumar_2020/Kumar_2020_genes_hg38_UCSC.bed")
genes_tss <- promoters(genes_loci, upstream = 2500, downstream = 2500)

filter_by_k27_group <- function(gr, df, group) {
  gr[gr$name %in% df[df$k27_bivalency_grp == group, "name"], ]
}

groups <- levels(genes$k27_bivalency_grp)
genes_k27_loci_groups <- lapply(groups, filter_by_k27_group, gr=genes_tss, df = genes)
names(genes_k27_loci_groups) <- groups

ns_gene_names <- genes %>% filter(k27_bivalency_grp == "None" & (H3K4m3_Ni_mean_cov > 2 | H3K4m3_Pr_mean_cov > 2)) %>% dplyr::select(name)
genes_k27_ns_w_k4 <- genes_tss[genes_tss$name %in% ns_gene_names$name, ]

plot_bw_heatmap_panel(
    c(bwfiles$k27[c(1, 3)], bwfiles$ub[c(1, 3)]),
    list(genes_k27_loci_groups$Pr_higher_than_Ni,
         genes_k27_loci_groups$Ni_higher_than_Pr,
         genes_k27_loci_groups$Always_up
    ),
    c("H3K27m3_Ni", "H3K27m3_Pr", "H2Aub_Ni", "H2Aub_Pr"),
    c("Primed >> Naive", "Naive >> Primed", "Always up"),
    global_scale = TRUE,
    proportional = TRUE,
    mode = "center"
)
```

Plot the second part of the heatmap panel.

```{r heatmap-groups-2, warning=F, fig.width = 14, fig.height = 10}

plot_bw_heatmap_panel(
  c(bwfiles$k27[c(1, 3)], bwfiles$ub[c(1, 3)]),
  list(genes_k27_loci_groups$Ni_higher_than_Pr, genes_k27_ns_w_k4),
  c("H3K27m3_Ni", "H3K27m3_Pr", "H2Aub_Ni", "H2Aub_Pr"),
  c("Primed >> Naive", "Rest"),
  global_scale = TRUE,
  proportional = TRUE,
  mode = "center",
  zmin = 0,
  zmax = 23
)

```

Plot the H3K4m3 part, sorted by the same reference

```{r heatmap-groups-3, warning=F, fig.width = 14, fig.height = 14}

plot_bw_heatmap_panel(
    c(bwfiles$k27[1], bwfiles$k4[c(1, 3)]),
    list(genes_k27_loci_groups$Pr_higher_than_Ni,
         genes_k27_loci_groups$Ni_higher_than_Pr,
         genes_k27_loci_groups$Always_up
    ),
    c("H3K27m3_Ni", "H3K4m3_Ni", "H3K4m3_Pr"),
    c("Primed >> Naive", "Naive >> Primed", "Always up"),
    global_scale = TRUE,
    proportional = TRUE,
    mode = "center"
)
```


# RNA-seq ratios at H3K27m3 groups

## H327m3 Naive >> Primed

```{r rnaseq-ratio-violin-h3k27m3-ni-higher, warning = F, message = F}

df <-
  genes[, c(
    "name",
    "RNASeq_DS_Pr_vs_Ni_log2FoldChange",
    "RNASeq_DS_EZH2i_vs_Ni_log2FoldChange",
    "RNASeq_DS_EZH2i_vs_Pr_log2FoldChange"
  )]

colnames(df) <- c("name", "Primed vs Naive", "EZH2i vs Naive", "EZH2i vs Primed")
df_k27_up <- df[df$name %in% genes_k27_loci_groups$Ni_higher_than_Pr$name, ]

df_long <- df %>% pivot_longer(!name, names_to = "group", values_to = "fc")
df_long_k27 <- df_k27_up %>% pivot_longer(!name, names_to = "group", values_to = "fc")

df_long$group <- factor(df_long$group, levels = c("Primed vs Naive", "EZH2i vs Naive", "EZH2i vs Primed"))
df_long_k27$group <- factor(df_long_k27$group, levels = c("Primed vs Naive", "EZH2i vs Naive", "EZH2i vs Primed"))

# Stats subset vs global
ni_pr_test <- wilcox.test(df_k27_up[, "Primed vs Naive"],
  df[!df$name %in% df_k27_up$name , "Primed vs Naive"], na.rm = T)

ni_pr_effect <- cohen.d(df_k27_up[, "Primed vs Naive"],
  df[!df$name %in% df_k27_up$name , "Primed vs Naive"], na.rm = T)

col <- "EZH2i vs Naive"
ni_ezh2i_test <- wilcox.test(df_k27_up[, col],
  df[!df$name %in% df_k27_up$name , col], na.rm = T)

ni_ezh2i_effect <- cohen.d(df_k27_up[, col],
  df[!df$name %in% df_k27_up$name , col], na.rm = T)

col <- "EZH2i vs Primed"
pr_ezh2i_test <- wilcox.test(df_k27_up[, col],
  df[!df$name %in% df_k27_up$name , col], na.rm = T)

pr_ezh2i_effect <- cohen.d(df_k27_up[, col],
  df[!df$name %in% df_k27_up$name , col], na.rm = T)

stats_caption <- paste("Wilcoxon global vs. selection",
  paste("Ni_Pr:", format(ni_pr_test$p.value, digits=8),
        "Cohen D:", round(ni_pr_effect$estimate, digits = 4),
        "(", ni_pr_effect$magnitude, ")"),
  paste("Ni_EZH2i:", format(ni_ezh2i_test$p.value, digits=8),
        "Cohen D:", round(ni_ezh2i_effect$estimate, digits = 4),
        "(", ni_ezh2i_effect$magnitude, ")"),
  paste("Pr_EZH2i:", format(pr_ezh2i_test$p.value, digits=8),
        "Cohen D:", round(pr_ezh2i_effect$estimate, digits = 4),
        "(", pr_ezh2i_effect$magnitude, ")"),
  sep = "\n")

my_comparisons <- list(c("EZH2i vs Naive", "EZH2i vs Primed"),
                       c("Primed vs Naive", "EZH2i vs Naive"),
                       c("Primed vs Naive", "EZH2i vs Primed"))

k27_up_color <- "#009784"

ggplot(data=df_long, aes(x = group, y = fc)) +
  geom_violin(size = 0.8) +
  stat_compare_means(data=df_long_k27,
    comparisons = my_comparisons, method = "wilcox.test", paired = TRUE) +
  rasterize(
    geom_jitter(data=df_long_k27, color = k27_up_color, alpha = 0.7, size = 0.1),
    dpi = 300) +
  geom_hline (yintercept = 0, linetype = "dashed") + 
  coord_cartesian(ylim = c(-13, 24)) +
  theme_default(base_size = 14) + 
  labs(x = "Condition",
       y = "Log2 FC",
       title = "RNASeq expression changes",
       subtitle = "Global vs H3K27m3 Naïve >> Primed TSS",
       caption = stats_caption)

write.table(df_long[!is.na(df_long$fc), ],
  file = "./figures_data/fig3_violin_k27_ni_higher_violin.tsv",
  col.names = T, sep = "\t", quote = F, row.names = F)

write.table(df_long_k27[!is.na(df_long_k27$fc), ],
  file = "./figures_data/fig3_violin_k27_ni_higher_jitter_k27_values.tsv",
  col.names = T, sep = "\t", quote = F, row.names = F)


```

## H327m3 Primed >> Naive

```{r rnaseq-ratio-violin-h3k27m3-pr-higher, warning = F, message = F}

df <-
  genes[, c(
    "name",
    "RNASeq_DS_Pr_vs_Ni_log2FoldChange",
    "RNASeq_DS_EZH2i_vs_Ni_log2FoldChange",
    "RNASeq_DS_EZH2i_vs_Pr_log2FoldChange"
  )]

colnames(df) <- c("name", "Primed vs Naive", "EZH2i vs Naive", "EZH2i vs Primed")

df_k27_up <- df[df$name %in% genes_k27_loci_groups$Pr_higher_than_Ni$name, ]

df_k27_up$`Primed vs Naive` <- -df_k27_up$`Primed vs Naive`
df$`Primed vs Naive` <- -df$`Primed vs Naive`

df_long <- df %>% pivot_longer(!name, names_to = "group", values_to = "fc")
df_long_k27 <- df_k27_up %>% pivot_longer(!name, names_to = "group", values_to = "fc")

df_long$group <- factor(df_long$group, levels = c("Primed vs Naive", "EZH2i vs Naive", "EZH2i vs Primed"))
df_long_k27$group <- factor(df_long_k27$group, levels = c("Primed vs Naive", "EZH2i vs Naive", "EZH2i vs Primed"))

levels(df_long$group) <- c("Naive vs Primed", "EZH2i vs Naive", "EZH2i vs Primed")
levels(df_long_k27$group) <- c("Naive vs Primed", "EZH2i vs Naive", "EZH2i vs Primed")

my_comparisons <- list(c("EZH2i vs Naive", "EZH2i vs Primed"),
                       c("Naive vs Primed", "EZH2i vs Naive"),
                       c("Naive vs Primed", "EZH2i vs Primed"))

# Stats subset vs global
ni_pr_test <- wilcox.test(df_k27_up[, "Primed vs Naive"],
  df[!df$name %in% df_k27_up$name , "Primed vs Naive"], na.rm = T)

ni_pr_effect <- cohen.d(df_k27_up[, "Primed vs Naive"],
  df[!df$name %in% df_k27_up$name , "Primed vs Naive"], na.rm = T)

col <- "EZH2i vs Naive"
ni_ezh2i_test <- wilcox.test(df_k27_up[, col],
  df[!df$name %in% df_k27_up$name , col], na.rm = T)

ni_ezh2i_effect <- cohen.d(df_k27_up[, col],
  df[!df$name %in% df_k27_up$name , col], na.rm = T)

col <- "EZH2i vs Primed"
pr_ezh2i_test <- wilcox.test(df_k27_up[, col],
  df[!df$name %in% df_k27_up$name , col], na.rm = T)

pr_ezh2i_effect <- cohen.d(df_k27_up[, col],
  df[!df$name %in% df_k27_up$name , col], na.rm = T)

stats_caption <- paste("Wilcoxon global vs. selection",
  paste("Ni_Pr:", format(ni_pr_test$p.value, digits=8),
        "Cohen D:", round(ni_pr_effect$estimate, digits = 4),
        "(", ni_pr_effect$magnitude, ")"),
  paste("Ni_EZH2i:", format(ni_ezh2i_test$p.value, digits=8),
        "Cohen D:", round(ni_ezh2i_effect$estimate, digits = 4),
        "(", ni_ezh2i_effect$magnitude, ")"),
  paste("Pr_EZH2i:", format(pr_ezh2i_test$p.value, digits=8),
        "Cohen D:", round(pr_ezh2i_effect$estimate, digits = 4),
        "(", pr_ezh2i_effect$magnitude, ")"),
  sep = "\n")

k27_up_color <- "#ff4b40"

ggplot(data=df_long, aes(x = group, y = fc)) +
  geom_violin(size = 0.8) +
  stat_compare_means(
    data=df_long_k27, comparisons = my_comparisons,
    method = "wilcox.test", paired = TRUE) +
  rasterize(
    geom_jitter(data=df_long_k27, color = k27_up_color, alpha = 0.7, size = 0.1),
    dpi = 300) +
  geom_hline (yintercept = 0, linetype = "dashed") + 
  coord_cartesian(ylim = c(-13, 24)) +
  theme_default(base_size = 14) + 
  labs(x = "Condition",
       y = "Log2 FC",
       title = "RNASeq expression changes",
       subtitle = "Global vs H3K27m3 Primed >> Naïve TSS",
       caption = stats_caption)


write.table(df_long[!is.na(df_long$fc), ],
  file = "./figures_data/fig3_violin_k27_pr_higher_violin.tsv",
  col.names = T, sep = "\t", quote = F, row.names = F)

write.table(df_long_k27[!is.na(df_long_k27$fc), ],
  file = "./figures_data/fig3_violin_k27_pr_higher_jitter_k27_values.tsv",
  col.names = T, sep = "\t", quote = F, row.names = F)


```

# Combined heatmaps

## Naive markers

```{r combined-summarized-heatmaps-naive, warning=F, message=F}
naive_markers <-
  c("KLF17",
    "DPPA5",
    "DNMT3L",
    "GATA6",
    "TBX3",
    "IL6ST",
    "DPPA3",
    "KLF5",
    "KLF4",
    "HORMAD1",
    "KHDC3L",
    "ALPP",
    "ALPPL2",
    "ZNF729",
    "TRIM60"
  )
combined_heatmap(genes, naive_markers) 
```

## Primed markers

```{r combined-summarized-heatmaps-primed, warning=F, message=F}
primed_markers <-
  c("CD24",
    "ZIC2",
    "SFRP2",
    "OTX2",
    "CYTL1",
    "HMX2",
    "THY1",
    "DUSP6",
    "PTPRZ1"
  )
combined_heatmap(genes, primed_markers) 
```
